trigger: none

resources:
  repositories:
    - repository: corePipelineTemplates
      type: github
      name: tumsky12/CorePipelineTemplates
      endpoint: GitHubConnection
      ref: refs/tags/1.0.2
    - repository: terraformModules
      type: github
      name: tumsky12/CoreTerraformModules
      endpoint: GitHubConnection
      ref: refs/tags/1.0.2

variables:
- group: shared-variable-group
- name: CoreInfrastructure
- name: workingDirectory
  value: $(System.DefaultWorkingDirectory)/SharedInfrastructure/CoreInfrastructure/Terraform
- name: backendAzureRmContainerName
  value: core-infrastructure
- name: devTfVarsFile
  value: dev.tfvars
- name: stgTfVarsFile
  value: stg.tfvars
- name: prdTfVarsFile
  value: prd.tfvars

extends:
  template: Templates/Stages/Terraform/terraform-apply-envs-stage.yml@corePipelineTemplates
  parameters:
    destroy: true
    environments:
      # - envName: dev
      #   infrastructureName: ${{ variables.infrastructureName }}
      #   workingDirectory: ${{ variables.workingDirectory }}
      #   backendAzureRmResourceGroupName: $(devBackendAzureRmResourceGroupName)
      #   backendAzureRmStorageAccountName: $(devBackendAzureRmStorageAccountName)
      #   backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
      #   tfVarsFile: ${{ variables.devTfVarsFile }}
      # - envName: stg
      #   dependsOn: dev
      #   infrastructureName: ${{ variables.infrastructureName }}
      #   workingDirectory: ${{ variables.workingDirectory }}
      #   backendAzureRmResourceGroupName: $(stgBackendAzureRmResourceGroupName)
      #   backendAzureRmStorageAccountName: $(stgBackendAzureRmStorageAccountName)
      #   backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
      #   tfVarsFile: ${{ variables.stgTfVarsFile }}        
      - envName: prd
        # dependsOn: stg
        infrastructureName: ${{ variables.infrastructureName }}
        workingDirectory: ${{ variables.workingDirectory }}
        backendAzureRmResourceGroupName: $(prdBackendAzureRmResourceGroupName)
        backendAzureRmStorageAccountName: $(prdBackendAzureRmStorageAccountName)
        backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
        tfVarsFile: ${{ variables.prdTfVarsFile }}       
