jobs:
- template: ../PipelineTemplates/Jobs/Terraform/terraform-destroy-job.yml
  parameters:
    name: 'Core'
    terraformWorkingDir: '$(System.DefaultWorkingDirectory)/CoreInfrastructure/Terraform'
    backendAzureRmContainerName: 'shared-core-tf-storage'

