trigger: none

resources:
  repositories:
    - repository: corePipelineTemplates
      type: github
      name: tumsky12/CorePipelineTemplates
      endpoint: GitHubConnection
      ref: refs/heads/feature/multiple-env-and-infra
    - repository: terraformModules
      type: github
      name: tumsky12/CoreTerraformModules
      endpoint: GitHubConnection
      ref: refs/tags/1.0.2

variables:
- group: shared-variable-group

- name: devTfVarsFile
  value: dev.tfvars
- name: stgTfVarsFile
  value: stg.tfvars
- name: prdTfVarsFile
  value: prd.tfvars

extends:
  template: Templates/Stages/Terraform/terraform-apply-envs-stage.yml@corePipelineTemplates
  parameters:
    destroy: false
    environments:
      # - envName: dev
      #   infrastructureName: ${{ variables.infrastructureName }}
      #   workingDirectory: ${{ variables.workingDirectory }}
      #   backendAzureRmResourceGroupName: $(devBackendAzureRmResourceGroupName)
      #   backendAzureRmStorageAccountName: $(devBackendAzureRmStorageAccountName)
      #   backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
      #   tfVarsFile: ${{ variables.devTfVarsFile }}
      # - envName: stg
      #   dependsOn: dev
      #   infrastructureName: ${{ variables.infrastructureName }}
      #   workingDirectory: ${{ variables.workingDirectory }}
      #   backendAzureRmResourceGroupName: $(stgBackendAzureRmResourceGroupName)
      #   backendAzureRmStorageAccountName: $(stgBackendAzureRmStorageAccountName)
      #   backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
      #   tfVarsFile: ${{ variables.stgTfVarsFile }}        
      - envName: prd
        # dependsOn: stg
        backendAzureRmResourceGroupName: $(prdBackendAzureRmResourceGroupName)
        backendAzureRmStorageAccountName: $(prdBackendAzureRmStorageAccountName)

    infrastructureGroups:
      - infrastructureName: SharedInfrastructure
        dependsOn: []
        workingDirectory: $(System.DefaultWorkingDirectory)/SharedInfrastructure/SharedInfrastructure/Terraform
        backendAzureRmContainerName: shared-infrastructure
        tfVarsFile: ${{ variables.prdTfVarsFile }}

      - infrastructureName: CoreInfrastructure
        dependsOn: []
        workingDirectory: $(System.DefaultWorkingDirectory)/SharedInfrastructure/CoreInfrastructure/Terraform
        backendAzureRmContainerName: core-infrastructure
        tfVarsFile: ${{ variables.prdTfVarsFile }}        
            