trigger: none

resources:
  repositories:
    - repository: corePipelineTemplates
      type: github
      name: tumsky12/CorePipelineTemplates
      endpoint: GitHubConnection
      ref: refs/heads/feature/multiple-env-and-infra
    - repository: terraformModules
      type: github
      name: tumsky12/CoreTerraformModules
      endpoint: GitHubConnection
      ref: refs/tags/1.0.2

variables:
- group: shared-variable-group

- name: devTfVarsFile
  value: dev.tfvars
- name: stgTfVarsFile
  value: stg.tfvars
- name: prdTfVarsFile
  value: prd.tfvars

extends:
  template: Templates/Stages/Terraform/terraform-apply-envs-stage.yml@corePipelineTemplates
  parameters:
    destroy: false
    environments:
      - envName: dev
        backendAzureRmResourceGroupName: $(devBackendAzureRmResourceGroupName)
        backendAzureRmStorageAccountName: $(devBackendAzureRmStorageAccountName)
        tfVarsFile: ${{ variables.devTfVarsFile }}

      - envName: stg
        dependsOn: dev
        backendAzureRmResourceGroupName: $(stgBackendAzureRmResourceGroupName)
        backendAzureRmStorageAccountName: $(stgBackendAzureRmStorageAccountName)
        tfVarsFile: ${{ variables.stgTfVarsFile }}

      - envName: prd
        dependsOn: stg
        backendAzureRmResourceGroupName: $(prdBackendAzureRmResourceGroupName)
        backendAzureRmStorageAccountName: $(prdBackendAzureRmStorageAccountName)
        tfVarsFile: ${{ variables.prdTfVarsFile }}

    infrastructureGroups:
      - infrastructureName: SharedInfrastructure
        dependsOn: []
        deployOn: [dev, prd]
        workingDirectory: $(System.DefaultWorkingDirectory)/SharedInfrastructure/SharedInfrastructure/Terraform
        backendAzureRmContainerName: shared-infrastructure

      - infrastructureName: CoreInfrastructure
        dependsOn: []
        deployOn: [stg, prd]
        workingDirectory: $(System.DefaultWorkingDirectory)/SharedInfrastructure/CoreInfrastructure/Terraform
        backendAzureRmContainerName: core-infrastructure
            