parameters:
- name: name
- name: workingDirectory
- name: backendAzureRmContainerName
- name: environmentServiceName
  default: 'Workload Identity Federation Connection'
- name: backendAzureRmResourceGroupName
- name: backendAzureRmResourceGroupLocation
  default: 'uksouth'  
- name: backendAzureRmStorageAccountName
- name: backendAzureRmKey
  default: 'terraform.tfstate'
- name: dependsOn
  default: []
  type: object
- name: planCommandOptions
  default: ''

jobs:
- job: ${{ parameters.name }}
  dependsOn: ${{ parameters.dependsOn }}
  displayName: 'Terraform Destroy ${{ parameters.name }} Infrastructure'
  steps:
  - template: ../../Steps/Terraform/terraform-install-step.yml
    parameters:
      name: ${{ parameters.name }}
  - template: ../../Steps/Terraform/terraform-check-formatting-step.yml
    parameters:
      name: ${{ parameters.name }}
  - template: ../../Steps/Terraform/terraform-init-step.yml
    parameters:
      name: ${{ parameters.name }}
      environmentServiceName: ${{ parameters.environmentServiceName }}
      backendAzureRmResourceGroupName: ${{ parameters.backendAzureRmResourceGroupName }}
      backendAzureRmResourceGroupLocation: ${{ parameters.backendAzureRmResourceGroupLocation }}
      backendAzureRmStorageAccountName: ${{ parameters.backendAzureRmStorageAccountName }}
      backendAzureRmContainerName: ${{ parameters.backendAzureRmContainerName }}
      backendAzureRmKey: ${{ parameters.backendAzureRmKey }}
  - template: ../../Steps/Terraform/terraform-validate-step.yml
    parameters:
      name: ${{ parameters.name }}
      workingDirectory: ${{ parameters.workingDirectory }}
  - template: ../../Steps/Terraform/terraform-destroy-plan-step.yml
    parameters:
      name: ${{ parameters.name }}
      workingDirectory: ${{ parameters.workingDirectory }}
      environmentServiceName: ${{ parameters.environmentServiceName }}
      planCommandOptions: ${{ parameters.planCommandOptions }}
  - template: ../../Steps/Terraform/terraform-destroy-step.yml
    parameters:
      name: ${{ parameters.name }}
      workingDirectory: ${{ parameters.workingDirectory }}
      environmentServiceName: ${{ parameters.environmentServiceName }}