parameters:
- name: name
- name: terraformWorkingDir
- name: backendAzureRmContainerName
- name: environmentServiceName
  default: 'Workload Identity Federation Connection'
- name: backendAzureRmResourceGroupName
  default: 'terraform-prod'
- name: backendAzureRmStorageAccountName
  default: 'terraformprod1784531786'
- name: backendAzureRmKey
  default: 'terraform-prod'
- name: dependsOn
  default: []
  type: object
- name: planCommandOptions
  default: ''

jobs:
- job: ${{ parameters.name }}
  dependsOn: ${{ parameters.dependsOn }}
  displayName: 'Terraform Destroy ${{ parameters.name }} Infrastructure'
  steps:
  - template: ../../Steps/Terraform/terraform-install-step.yml
    parameters:
      name: ${{ parameters.name }}
  - template: ../../Steps/Terraform/terraform-check-formatting-step.yml
    parameters:
      name: ${{ parameters.name }}
  - template: ../../Steps/Terraform/terraform-init-step.yml
    parameters:
      name: ${{ parameters.name }}
      terraformWorkingDir: ${{ parameters.terraformWorkingDir }}
      backendAzureRmContainerName: ${{ parameters.backendAzureRmContainerName }}
      environmentServiceName: ${{ parameters.environmentServiceName }}
      backendAzureRmResourceGroupName: ${{ parameters.backendAzureRmResourceGroupName }}
      backendAzureRmStorageAccountName: ${{ parameters.backendAzureRmStorageAccountName }}
      backendAzureRmKey: ${{ parameters.backendAzureRmKey }}
  - template: ../../Steps/Terraform/terraform-validate-step.yml
    parameters:
      name: ${{ parameters.name }}
      terraformWorkingDir: ${{ parameters.terraformWorkingDir }}
  - template: ../../Steps/Terraform/terraform-destroy-plan-step.yml
    parameters:
      name: ${{ parameters.name }}
      terraformWorkingDir: ${{ parameters.terraformWorkingDir }}
      environmentServiceName: ${{ parameters.environmentServiceName }}
      planCommandOptions: ${{ parameters.tfPlanCommandOptions }}
  - template: ../../Steps/Terraform/terraform-destroy-step.yml
    parameters:
      name: ${{ parameters.name }}
      terraformWorkingDir: ${{ parameters.terraformWorkingDir }}
      environmentServiceName: ${{ parameters.environmentServiceName }}