parameters:
- name: name
- name: dependsOn
  type: object
  default: []

jobs:
- template: ../PipelineTemplates/Jobs/Terraform/terraform-apply-job.yml
  parameters:
    name: ${{ parameters.name }}
    workingDirectory: '$(System.DefaultWorkingDirectory)/SharedInfrastructure/Terraform'
    backendAzureRmContainerName: 'shared-shared-tf-storage'
    dependsOn: ${{ parameters.dependsOn }}
