parameters:
  - name: environments
    type: object
    default:
      envName: 'name'
      dependsOn: []
      infrastructureName: 'infrastructureName'
      backendAzureRmResourceGroupName: 'backendAzureRmResourceGroupName'

stages:
  - ${{ each env in parameters.environments}}:
    - stage: ${{ env.envName }}
      jobs: 
      - template: Templates\Jobs\Terraform\terraform-apply-job.yml@corePipelineTemplates
        parameters:
          name: 'foo'
          workingDirectory: '$(System.DefaultWorkingDirectory)/SharedInfrastructure/Terraform'
          backendAzureRmResourceGroupName: terraform-dev
          backendAzureRmResourceGroupLocation: uksouth
          backendAzureRmStorageAccountName: terraformdev8716912495
          backendAzureRmContainerName: baa
          backendAzureRmKey: terraform.tfstate