parameters:
  - name: environments
    type: object
    default:
      envName: 'name'
      dependsOn: []
      infrastructureName: 'infrastructureName'
      workingDirectory: 'workingDirectory'
      backendAzureRmResourceGroupName: 'backendAzureRmResourceGroupName'
      backendAzureRmStorageAccountName: 'backendAzureRmStorageAccountName'
      backendAzureRmContainerName: 'backendAzureRmContainerName'
      tfVarsFile: 'tfVarsFile'

stages:
  - ${{ each env in parameters.environments}}:
    - stage: ${{ env.envName }}
      dependsOn: ${{ env.dependsOn }}
      jobs: 
      - template: Templates\Jobs\Terraform\terraform-apply-job.yml@corePipelineTemplates
        parameters:
          name: ${{ env.infrastructureName }}
          workingDirectory: ${{ env.workingDirectory }}
          backendAzureRmResourceGroupName: ${{ env.backendAzureRmResourceGroupName }}
          backendAzureRmStorageAccountName: ${{ env.backendAzureRmStorageAccountName }}
          backendAzureRmContainerName: ${{ env.backendAzureRmContainerName }}
          planCommandOptions: '-var-file="EnvironmentVariables/${{ env.tfVarsFile }}"'
