trigger: none

resources:
  repositories:
    - repository: corePipelineTemplates
      type: github
      name: tumsky12/CorePipelineTemplates
      endpoint: GitHubConnection
      ref:  'refs/heads/feature/multiple-environment-deployment'
      # ref: refs/tags/1.0.1
    - repository: terraformModules
      type: github
      name: tumsky12/CoreTerraformModules
      endpoint: GitHubConnection
      ref: refs/tags/1.0.0

variables:
  infrastructureName: SharedInfrastructure
  workingDirectory: '$(System.DefaultWorkingDirectory)/SharedInfrastructure/SharedInfrastructure/Terraform'
  backendAzureRmContainerName: shared-infrastructure
  devTfVarsFile: dev.tfvars
  stgTfVarsFile: stg.tfvars
  prdTfVarsFile: prd.tfvars

extends:
  template: Templates/Stages/Terraform/terraform-apply-envs-stage.yml@corePipelineTemplates
  parameters:
    destroy: true
    environments:
      - envName: dev
        infrastructureName: ${{ variables.infrastructureName }}
        workingDirectory: ${{ variables.workingDirectory }}
        backendAzureRmResourceGroupName: ${{ variables.devBackendAzureRmResourceGroupName }}
        backendAzureRmStorageAccountName: ${{ variables.devBackendAzureRmStorageAccountName }}
        backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
        tfVarsFile: ${{ variables.devTfVarsFile }}
      - envName: stg
        dependsOn: dev
        infrastructureName: ${{ variables.infrastructureName }}
        workingDirectory: ${{ variables.workingDirectory }}
        backendAzureRmResourceGroupName: ${{ variables.stgBackendAzureRmResourceGroupName }}
        backendAzureRmStorageAccountName: ${{ variables.stgBackendAzureRmStorageAccountName }}
        backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
        tfVarsFile: ${{ variables.stgTfVarsFile }}        
      - envName: prd
        dependsOn: stg
        infrastructureName: ${{ variables.infrastructureName }}
        workingDirectory: ${{ variables.workingDirectory }}
        backendAzureRmResourceGroupName: ${{ variables.prdBackendAzureRmResourceGroupName }}
        backendAzureRmStorageAccountName: ${{ variables.prdBackendAzureRmStorageAccountName }}
        backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
        tfVarsFile: ${{ variables.prdTfVarsFile }}       
