trigger: none

resources:
  repositories:
    - repository: corePipelineTemplates
      type: github
      name: tumsky12/CorePipelineTemplates
      endpoint: GitHubConnection
      ref:  'refs/heads/feature/multiple-environment-deployment'
      # ref: refs/tags/1.0.1
    - repository: terraformModules
      type: github
      name: tumsky12/CoreTerraformModules
      endpoint: GitHubConnection
      ref: refs/tags/1.0.0

variables:
  infrastructureName: SharedInfrastructure
  workingDirectory: $(System.DefaultWorkingDirectory)/SharedInfrastructure/SharedInfrastructure/Terraform
  backendAzureRmContainerName: shared-infrastructure
  devTfVarsFile: dev.tfvars
  stgTfVarsFile: stg.tfvars
  prdTfVarsFile: prd.tfvars

extends:
  template: Templates/Stages/Terraform/terraform-apply-envs-stage.yml@corePipelineTemplates
  parameters:
    destroy: true
    environments:
      - envName: dev
        infrastructureName: SharedInfrastructure
        workingDirectory: $(workingDirectory)
        backendAzureRmResourceGroupName: $(devBackendAzureRmResourceGroupName)
        backendAzureRmStorageAccountName: $(devBackendAzureRmStorageAccountName)
        backendAzureRmContainerName: $(backendAzureRmContainerName)
        tfVarsFile: $(devTfVarsFile)
      - envName: stg
        dependsOn: dev
        infrastructureName: $(infrastructureName)
        workingDirectory: $(workingDirectory)
        backendAzureRmResourceGroupName: $(stgBackendAzureRmResourceGroupName)
        backendAzureRmStorageAccountName: $(stgBackendAzureRmStorageAccountName)
        backendAzureRmContainerName: $(backendAzureRmContainerName)
        tfVarsFile: $(stgTfVarsFile)        
      - envName: prd
        dependsOn: stg
        infrastructureName: $(infrastructureName)
        workingDirectory: $(workingDirectory)
        backendAzureRmResourceGroupName: $(prdBackendAzureRmResourceGroupName)
        backendAzureRmStorageAccountName: $(prdBackendAzureRmStorageAccountName)
        backendAzureRmContainerName: $(backendAzureRmContainerName)
        tfVarsFile: $(prdTfVarsFile)       
