trigger: none

resources:
  repositories:
    - repository: corePipelineTemplates
      type: github
      name: tumsky12/CorePipelineTemplates
      endpoint: GitHubConnection
    - repository: terraformModules
      type: github
      name: tumsky12/CoreTerraformModules
      endpoint: GitHubConnection
    # - repository: corePipelineTemplates
    #   type: github
    #   name: tumsky12/CorePipelineTemplates
    #   ref: refs/tags/1.0.0
    #   # ref:  'refs/heads/init-changes'
    #   endpoint: GitHubConnection
    # - repository: terraformModules
    #   type: github
    #   name: tumsky12/CoreTerraformModules
    #   ref:  'refs/heads/main'
    #   endpoint: GitHubConnection

variables:
  infrastructureName: SharedInfrastructure
  backendAzureRmContainerName: shared-tf-storage

extends:
  template: terraform-apply-envs-stage.yml@self
  parameters:
    destroy: true
    environments:
      - envName: dev
        infrastructureName: SharedInfrastructure
        workingDirectory: $(System.DefaultWorkingDirectory)/SharedInfrastructure/SharedInfrastructure/Terraform
        backendAzureRmResourceGroupName: rg-terraform-dev
        backendAzureRmStorageAccountName: terraformdev8716912495
        backendAzureRmContainerName: shared-infrastructure
        tfVarsFile: 'dev.tfvars'
      - envName: stg
        dependsOn: dev
        infrastructureName: SharedInfrastructure
        workingDirectory: $(System.DefaultWorkingDirectory)/SharedInfrastructure/SharedInfrastructure/Terraform
        backendAzureRmResourceGroupName: rg-terraform-stg
        backendAzureRmStorageAccountName: terraformstg4983265215
        backendAzureRmContainerName: shared-infrastructure
        tfVarsFile: 'stg.tfvars'        
      # - envName: prd
      #   dependsOn: stg
      #   infrastructureName: SharedInfrastructure
      #   workingDirectory: $(System.DefaultWorkingDirectory)/SharedInfrastructure/SharedInfrastructure/Terraform
      #   backendAzureRmResourceGroupName: rg-terraform-prd
      #   backendAzureRmStorageAccountName: terraformprd1784531786
      #   backendAzureRmContainerName: shared-infrastructure
      #   tfVarsFile: 'prd.tfvars'       
