parameters:
- name: name
- name: dependsOn
  default: []

jobs:
- template: ../PipelineTemplates/Jobs/Terraform/terraform-destroy-job.yml
  parameters:
    name: ${{ parameters.name }}
    terraformWorkingDir: '$(System.DefaultWorkingDirectory)/VirtualMachineInfrastructure/Terraform'
    backendAzureRmContainerName: 'shared-vm-tf-storage'
    dependsOn: ${{ parameters.dependsOn }}